[package]
name = "webgateway-mnt"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.101"
clap = { version = "4.5.59", features = ["derive"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
shared = { version = "0.1.0", path = "../crates/shared" }
